// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjeiuepgiowjrhjotgdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqZWl1ZXBnaW93anJoam90Z2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzE0MTcsImV4cCI6MjA2Mzk0NzQxN30.16CTYOn7jDzxYJ8icNHe1GgMOudSJ3dJ0rJElFx950M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);